AtiWrapperServicesUI/AtiWrapperServicesUI/Models/ServiceMethodParameterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AtiWrapperServicesUI.Models
{
    public class ServiceMethodParameterViewModel
    {
        public string ServiceMethodName { get; set; }
        public string WrapperMethodName { get; set; }
        public string SoapHeaderTypeName { get; set; }
        public List<ParameterViewModel> SoapHeaders { get; set; }
        public List<ParameterViewModel> Parameters { get; set; }
    }

    public class WrapperMethodParameterViewModel
    {
        public string CustomerName { get; set; }
        public string ServiceMethodName { get; set; }
        public string WrapperMethodName { get; set; }
        public string SoapHeaderTypeName { get; set; }
        public List<ParameterDefaultViewModel> SoapHeaders { get; set; }
        public List<ParameterDefaultViewModel> Parameters { get; set; }
    }

    
    public class ParameterViewModel
    {
        public string Name { get; set; }
        public string TypeName { get; set; }
        public Object Value { get; set; }
    }


    public class ParameterDefaultViewModel : ParameterViewModel
    {
        public int Id { get; set; }
        public bool Required { get; set; }
        public SelectList EnumList { get; set; }
    }
}

AtiWrapperServicesUI/AtiWrapperServicesUI/Controllers/CustomerServiceUrlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AtiWrapperServicesUI.Models;
using System.IO;
using System.Text;
using System.Reflection;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using DynamicServiceProxyNamespace;
using System.ServiceModel.Description;
using System.Xml.Serialization;
using System.ServiceModel.Channels;
using System.ServiceModel;
using CustomMessageHeaders.CustomSoapHeaders;
using CustomMessageHeaders;
using AtiWrapperServicesORM.OpenAccess;
using AtiWrapperServices.AtiWrapperServicesEnums;
using System.Diagnostics;


namespace AtiWrapperServicesUI.Controllers
{
    public class CustomerServiceUrlController : Controller
    {
        private const string CUSTOMSOAPHEADERSNAMESPACE = "CustomMessageHeaders.CustomSoapHeaders";

        
        private DynamicServiceProxyFactory serviceFactory;
        private DynamicServiceProxy serviceProxy;
        private readonly Assembly customMessageHeadersAssembly = typeof(HeaderDynamicProperty).Assembly;
        static public TraceSource TraceSource = new TraceSource("AtiServiceDataUI");
        //
        // GET: /CustomerServiceUrl/
        public static T Cast<T>(object o, T[] x)
        {
            T foo = (T)o;
            x[0] = (T)o;
            return (T)o;
        }

        private CustomerServiceUrlViewModel myModel;

        [HttpGet]
        public ActionResult Create()
        {
            if (TempData["Data"] == null)
            {
                myModel = new CustomerServiceUrlViewModel();
                myModel.EndpointAddressModifierOption = DynamicServiceProxyFactoryOptions.EndpointAddressModifierOptions.UseMetadataAddress;
            }
            else
            {
                myModel = TempData["Data"] as CustomerServiceUrlViewModel;
            }

            if (TempData["ServiceFactory"] != null)
            {
                serviceFactory = TempData["ServiceFactory"] as DynamicServiceProxyFactory;
            }

            var selectCustomSoapHeaders = (from h in customMessageHeadersAssembly.GetTypes()
                                           where h.IsClass
                                           select new SelectListItem { Text = h.Name, Value = h.Name });
            
            myModel.CustomSoapHeaderList = new SelectList(selectCustomSoapHeaders, "Value", "Text");

           

            if (myModel.TestUseSource.Equals(UseSource.Wsdl))
            {
                GetServiceNamesFromWsdl(myModel.TestUrl);
            }

            if (myModel.ServiceName != null)
            {
                GetServiceMethods(myModel.ServiceName);
            }

            return View(myModel);
        }

        [HttpPost]
        public ActionResult Create(CustomerServiceUrlViewModel data, string command)
        {
            myModel = data;
            Trace.CorrelationManager.ActivityId = Guid.NewGuid();
            Trace.CorrelationManager.StartLogicalOperation("CustomerServiceUrlController Create");
            TraceSource.TraceEvent(TraceEventType.Start, 1000, "CustomerServiceUrlController Create Post");
            
            if (command == "FlattenReturn")
            {
                //TempData["Data"] = data;
                //myModel.FlatReturnType = wsdlWebService.GetFlatReturnTypes(myModel.ServiceMethod);
                //TempData["Data"] = myModel;
                //return RedirectToAction("ReturnTypeTable");
                TraceSource.TraceEvent(TraceEventType.Stop, 2001);
            }
            else if (command == "FlattenParameters")
            {
                //TempData["Data"] = data;
                //myModel.FlatParameters = wsdlWebService.GetFlatParameterTypes(myModel.ServiceMethod);
                //TempData["Data"] = myModel;
                //return RedirectToAction("ParameterTypeTable");
                TraceSource.TraceEvent(TraceEventType.Stop, 2002);
            }
            else if (command == "Test")
            {
                TempData["Data"] = data;
                TraceSource.TraceEvent(TraceEventType.Stop, 2003);
                return RedirectToAction("TestServiceMethod");
            }
            else if (command == "ChangeAddress")
            {
                data.EndpointAddressModifierOption = DynamicServiceProxyFactoryOptions.EndpointAddressModifierOptions.MakeSameAsUrl;
                TempData["Data"] = data;
                DynamicServiceProxyFactoryOptions options = new DynamicServiceProxyFactoryOptions();
                options.EndpointAddress = DynamicServiceProxyFactoryOptions.EndpointAddressModifierOptions.MakeSameAsUrl;
                serviceFactory = new DynamicServiceProxyFactory(data.TestUrl + "?wsdl", options);
                TempData["ServiceFactory"] = serviceFactory;
                TraceSource.TraceEvent(TraceEventType.Stop, 2004);
                return RedirectToAction("Create");
            }
            else if (command == "Save")
            {
                TraceSource.TraceEvent(TraceEventType.Stop, 2005);
                TempData["Data"] = data;
                serviceProxy = TempData["ServiceProxy"] as DynamicServiceProxy;

                if (ModelState.IsValid)
                {
                    DynamicServiceProxyFactoryOptions options = new DynamicServiceProxyFactoryOptions();
                    options.EndpointAddress = DynamicServiceProxyFactoryOptions.EndpointAddressModifierOptions.MakeSameAsUrl;
                    serviceFactory = new DynamicServiceProxyFactory(data.TestUrl + "?wsdl", options);
                    SaveServiceMethodData(data, serviceFactory);
                }
            }

            var selectCustomSoapHeaders = (from h in customMessageHeadersAssembly.GetTypes()
                                           where h.IsClass
                                           select new SelectListItem { Text = h.Name, Value = h.Name });
            data.CustomSoapHeaderList = new SelectList(selectCustomSoapHeaders, "Value", "Text");
            TraceSource.TraceEvent(TraceEventType.Stop, 2006);
            return View(data);
        }

        private List<TypeData> GetInputParamaterList(CustomerServiceUrlViewModel data)
        {
            List<TypeData> inputParametersList = new List<TypeData>();
            MethodInfo methodInfo = serviceProxy.ProxyType.GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly)
                                     .First(m => m.Name == data.ServiceMethod);

            foreach (ParameterInfo p in methodInfo.GetParameters())
            {
                GetParameterNameTypeList(inputParametersList, p.ParameterType.GetTypeInfo(), p.Name, String.Empty);
            }

            return inputParametersList;
        }

        private void GetParameterNameTypeList(List<TypeData> parameterNameTypeList, TypeInfo parameterTypeInfo, string name, string prefix)
        {
            if (parameterTypeInfo.FullName.Equals("System.Runtime.Serialization.ExtensionDataObject"))
            {
                return;
            }
            if (parameterTypeInfo.Namespace == "System")
            {
                if (parameterTypeInfo.IsByRef)
                {
                    parameterNameTypeList.Add(new TypeData { Name = String.IsNullOrEmpty(prefix) ? name : prefix + "." + name, Type = parameterTypeInfo.FullName.TrimEnd('&') });
                }
                else
                {
                    parameterNameTypeList.Add(new TypeData { Name = String.IsNullOrEmpty(prefix) ? name : prefix + "." + name, Type = parameterTypeInfo.ToString() });
                }
            }
            //else if (parameterTypeInfo.BaseType != null && (parameterTypeInfo.BaseType.Equals(typeof(Enum)) || 
            //    (parameterTypeInfo.BaseType.Namespace != null && parameterTypeInfo.BaseType.Namespace.StartsWith("System"))))
            else if (parameterTypeInfo.BaseType != null && (parameterTypeInfo.BaseType.Equals(typeof(Enum)) || parameterTypeInfo.BaseType.IsGenericType))
            {
                var test = serviceProxy.ProxyType.Assembly.GetType(parameterTypeInfo.FullName, false);
                parameterNameTypeList.Add(new TypeData { Name = String.IsNullOrEmpty(prefix) ? name : prefix + "." + name, Type = parameterTypeInfo.FullName });
            }
            
            else
            {
                if (!String.IsNullOrEmpty(name))
                {
                    prefix = String.IsNullOrEmpty(prefix) ? name : prefix + "." + name;
                }
                foreach (PropertyInfo prop in parameterTypeInfo.DeclaredProperties)
                {
                    if (prop.PropertyType.FullName.Equals("System.Runtime.Serialization.ExtensionDataObject"))
                    {
                        continue;
                    }
                    if (prop.PropertyType.Namespace == "System")
                    {
                        parameterNameTypeList.Add(new TypeData { Name = String.IsNullOrEmpty(prefix) ? prop.Name : prefix + "." + prop.Name, Type = prop.PropertyType.ToString() });
                    }
                    else
                    {
                        GetParameterNameTypeList(parameterNameTypeList, serviceProxy.ProxyType.Assembly.DefinedTypes.First(m => m.Name == prop.PropertyType.Name),
                            prop.PropertyType.Name, String.IsNullOrEmpty(prefix) ? prop.PropertyType.Name : prefix + "." + prop.PropertyType.Name);
                    }
                }
                
                if (parameterTypeInfo.IsArray)
                {
                    GetParameterNameTypeList(parameterNameTypeList, serviceProxy.ProxyType.Assembly.DefinedTypes.First(m => m.Name == parameterTypeInfo.GetElementType().Name),

AtiWrapperServicesUI/AtiWrapperServicesUI/Views/OldCustomerServiceUrl/AddSoapHeaderView.cshtml
@model AtiWrapperServicesUI.Models.SoapHeaderModel

@{
    ViewBag.Title = "AddSoapHeaderView";
}


<h2>AddSoapHeaderView</h2>
    
    @using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>SoapHeader</legend>
        @Html.EditorFor(x => x.SoapHeader)

        <p>
            <input type="submit" value="AddSoapHeader" />
        </p>
    </fieldset>
}

AtiWrapperServicesUI/AtiWrapperServicesUI/Views/OldCustomerServiceUrl/Create.cshtml
@model AtiWrapperServicesUI.Models.CustomerServiceUrlViewModel

@{
    ViewBag.Title = "Create";
}



    

<h2>Create</h2>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Customer</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomerName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CustomerName)
            @Html.ValidationMessageFor(model => model.CustomerName)
        </div>
        <div class="editor-label" >
            @Html.LabelFor(model => model.TestUrl)
        </div>
        <div class="editor-field" >
            @Html.EditorFor(model => model.TestUrl)
            @Html.ValidationMessageFor(model => model.TestUrl)
        </div>
        <div class="editor-label" >
            @Html.LabelFor(model => model.ProductionUrl)
        </div>
        <div class="editor-field" >
            @Html.EditorFor(model => model.ProductionUrl)
            @Html.ValidationMessageFor(model => model.ProductionUrl)
        </div>
        <div class="editor-label" >
            @Html.LabelFor(model => model.ServiceName)
        </div>
        <div id="service-name-dropdown-container">
            @Html.Partial("_ServiceName")
        </div>
        <div class="editor-label" >
            @Html.LabelFor(model => model.ServiceMethod)
        </div>
        <div id="service-method-dropdown-container">
            @Html.Partial("_ServiceMethod")
        </div>
        @*<div id="service-type-tables-container">
            @Html.Partial("_TypeTables")
        </div>*@
        <div class="editor-label" >
            @Html.LabelFor(model => model.CustomSoapHeaderName)
        </div>
        <div class="editor-field" >
            @Html.DropDownListFor(model => model.CustomSoapHeaderName, Model.CustomSoapHeaderList, "[ --- None --- ]")
        </div>

        <span>
            <button type="submit" value="FlattenReturn" id="FlattenReturnTypes" name="Command">Flatten Return Types</button>
            <button type="submit" value="FlattenParameters" id="FlattenParameterTypes" name="Command">Flatten Parameter Types</button>
        </span>
        <p>
            <span>
                <button type="submit" value="Test" name="Command">Test Method</button>
                <button type="submit" value="Save" name="Command">Save</button>

            </span>
            
        </p>
    </fieldset>
}

@section Scripts {
    @*<script type="text/javascript">
        (function () {
            $(function () {
                $("#FlattenReturnTypes").live('click', function (e) {
                    var mName = $("#ServiceMethod").attr("value");
                    alert("Service Method is: " + mName);
                    var retUrl = '@Url.Content("~/CustomerServiceUrl/ReturnTypeTable?ServiceMethod=")';
                    var withMethod = retUrl + mName;
                    alert("Service Method Url: " + withMethod);
                    location.href = withMethod;
                });
            });
        })();
    </script>*@
    <script type="text/javascript">
        (function () {
            $(function () {
                function serviceTypes(e, element) {
                    var serviceMethod = element.attr("value");
                    var d = "serviceMethod=" + serviceMethod;
                    var actionURL = '@Url.Action("ServiceTypeTables", "CustomerServiceUrl")';
                    //alert("the name is: " + serviceMethod);
                     $.ajax({
                         type: "POST",
                         url: actionURL,
                         data: d,
                         success: function (r) {
                             //alert("success: " + r.data);
                             $("#service-type-tables-container").html(r.data);
                         },
                         complete: function () {
                             //alert("complete:");
                             $("#ServiceMethod").on('change', function (event) {
                             serviceTypes(event, $(this));
                             });
                         },
                         error: function (req, status, error) {
                             alert("error:");
                         }
                     });
                     e.preventDefault();
                 }
                 $("#ServiceMethod").on('change', function (e) {
                     //alert("attaching js");
                     serviceTypes(e, $(this));
                 });
             });
         })();
    </script>
     <script type="text/javascript">
         (function () {
             $(function () {
                 function serviceMethods(e, element) {
                     var serviceName = element.attr("value");
                     var d = "serviceName=" + serviceName;
                     var actionURL = '@Url.Action("ServiceMethodList", "CustomerServiceUrl")';
                    //alert("the name is: " + serviceName);
                    $.ajax({
                        type: "POST",
                        url: actionURL,
                        data: d,
                        success: function (r) {
                            //alert("success: " + r.data);
                            $("#service-method-dropdown-container").html(r.data);
                        },
                        complete: function () {
                            //alert("complete:");
                            $("#ServiceName").on('change', function (event) {
                                serviceMethods(event, $(this));
                            });
                        },
                        error: function (req, status, error) {
                            alert("error:");
                        }
                    });
                    e.preventDefault();
                }
                $("#ServiceName").on('change', function (e) {
                    //alert("attaching js");
                    serviceMethods(e, $(this));
                });
            });
        })();
    </script>
   <script type="text/javascript">
       (function () {
        $(function () {
            function serviceNames(e, element) {
                var url = element.attr("value");
                var d = "serviceUrl=" + url;
                var actionURL = '@Url.Action("ServiceNameList", "CustomerServiceUrl")';
                alert("the url is: " + url);
                $.ajax({
                    type: "POST",
                    url: actionURL,
                    data: d,
                    success: function (r) {
                        //alert("success: " + r.data);
                        $("#service-name-dropdown-container").html(r.data);
                    },
                    complete: function () {
                        //alert("complete:");
                        $("#TestUrl").on('change', function (event) {
                            serviceNames(event, $(this));
                        });
                    },
                    error: function (req, status, error) {
                        alert("error:");
                }
                });
                e.preventDefault();
            }
            $("#TestUrl").on('change', function (e) {
                serviceNames(e, $(this));
            });
        });
    })();
    </script>
    @*<script type="text/javascript">
        (function () {
            $(function () {
                function serviceNames(e, element) {
                    var url = element.attr("value");
                    var d = "serviceUrl=" + url;
                    var actionURL = '@Url.Action("Simple", "CustomerServiceUrl")';
                alert("the url is: " + url);
                $.ajax({
                    type: "POST",
                    url: actionURL,
                    data: d,
                    success: function (r) {
                        alert("success: " + r.data);
                        $("#service-name-dropdown-container").html(r.data);
                    },
                    complete: function () {
                        alert("complete:");
                        $("#TestUrl").on('change', function (event) {
                            serviceNames(event, $(this));
                        });
                    },
                    error: function (req, status, error) {
                        alert("error:");
                    }
                });
                e.preventDefault();
            }
            $("#TestUrl").on('change', function (e) {
                serviceNames(e, $(this));
            });
        });
       })();
    </script>*@
   
}

AtiWrapperServicesUI/AtiWrapperServicesUI/Views/OldCustomerServiceUrl/ServiceMethodParameterView.cshtml
@model AtiWrapperServicesUI.Models.ServiceMethodParameterViewModel

@{
    ViewBag.Title = "ServiceMethodParameterView";
}

<h2>ServiceMethodParameterView</h2>
@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.SoapHeaderTypeName)

    if (Model.SoapHeaders.Count > 0)
    {
        <div>
            <table>
                <thead>
                    <tr>
                        <td>
                            <h2>Name</h2>
                        </td>
                        <td>
                            <h2>Type</h2>
                        </td>
                        <td>
                            <h2>Value</h2>
                        </td>
                    </tr>
                </thead>

            @for (int i = 0; i < Model.SoapHeaders.Count; i++)
            {
                    @Html.EditorFor(x => x.SoapHeaders[i])
            }
            </table>
        </div>
    }
    <div>
        <table>
            <thead>
                <tr>
                    <td>
                        <h2>Name</h2>
                    </td>
                    <td>
                        <h2>Type</h2>
                    </td>
                    <td>
                        <h2>Value</h2>
                    </td>
                </tr>
            </thead>

        @for (int i = 0; i < Model.Parameters.Count; i++)
        {
                @Html.EditorFor(x => x.Parameters[i])
        }
        </table>
    </div>
<input type ="submit" value="OK" />
}

AtiWrapperServicesUI/AtiWrapperServicesUI/Views/OldCustomerServiceUrl/ServiceMethodResultView.cshtml
@model AtiWrapperServicesUI.Models.MethodResult

@{
    ViewBag.Title = "ServiceMethodResultView";
}

<h2>ServiceMethodResultView</h2>
<h3>@Model.request</h3>
<p>
@Model.result
</p>

AtiWrapperServicesUI/AtiWrapperServicesUI/Views/OldCustomerServiceUrl/_ServiceMethod.cshtml
@model AtiWrapperServicesUI.Models.CustomerServiceUrlViewModel

<div class="editor-field">
    @if (ViewBag.ServiceMethods != null)
    {
        @Html.DropDownListFor(model => model.ServiceMethod, (IEnumerable<SelectListItem>)ViewBag.ServiceMethods, "[ --- Select One --- ]")
    }
    else if (!String.IsNullOrEmpty(Model.ServiceMethod))
    { 
        @Html.DropDownListFor(model => model.ServiceMethod, new List<SelectListItem> { new SelectListItem { Text = Model.ServiceMethod, Value = Model.ServiceMethod}})
    }
    else
    {
        @Html.DropDownListFor(model => model.ServiceMethod, new List<SelectListItem> {} , "[ --- Selection Not Availaible ---]")
    }
</div>

AtiWrapperServicesUI/AtiWrapperServicesUI/Views/OldCustomerServiceUrl/_ServiceName.cshtml
@model AtiWrapperServicesUI.Models.CustomerServiceUrlViewModel


<div class="editor-field">
    @if (ViewBag.ServiceNames != null)
    {
        @Html.DropDownListFor(model => model.ServiceName, (IEnumerable<SelectListItem>)ViewBag.ServiceNames, "[ --- Select One --- ]")
    }
    else if (!String.IsNullOrEmpty(Model.ServiceName))
    { 
        @Html.DropDownListFor(model => model.ServiceName, new List<SelectListItem> { new SelectListItem { Text = Model.ServiceName, Value = Model.ServiceName}})
    }
    else
    {
        @Html.DropDownListFor(model => model.ServiceName, new List<SelectListItem> {} , "[ --- Selection Not Availaible ---]")
    }
</div>

@if (ViewBag.WsdlAddress != null && ViewBag.ServiceAddress != null)
{
    string serviceAddress = (string)@ViewBag.ServiceAddress;
    <span>
        @Html.Label("Wsdl Address")
        @Html.TextBox("WsdlAddress", (string)@ViewBag.WsdlAddress, new {@readonly = true})
    </span>
    <span>
        @Html.Label("Service Address")
        @Html.TextBox("ServiceAddress", serviceAddress, new {@readonly = true})
    </span>
    <span>
       @* @Html.Label("Make Addresses the Same")
        @Html.CheckBox("MakeSame", (bool?)@ViewBag.MakeSame)*@
        @*@Html.ActionLink("Use Service Address", "ChangeEndpointAddress", "CustomerServiceUrl", new { endpointAddress = serviceAddress }, null)*@
        <button type="submit" value="ChangeAddress" name="Command">Use Service Address</button>

    </span>        
}